# docker-compose.yml

services:
  postgres:
    image: postgres:17

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fullstack

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile

    ports:
      - "3000:3000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fullstack?schema=public
      PORT: 3000
      CORS_ORIGIN: http://localhost:4200

volumes:
  postgres-data: